# This will start a haproxy and three web services. haproxy will act as a loadbalancer.
# Authors: yeasy.github.com
# Date: 2015-11-15

version: "3.9"
services:
    haproxy:
        image: haproxy:2.7
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/ssl:/etc/ssl:ro
            - ./config/haproxy:/haproxy-override
            - ./config/haproxy/:/usr/local/etc/haproxy/
        ports:
            - "80:80"
            - "70:70" # haproxy admin console, login with user:pass
            - "443:443"
        environment:
            - VIRTUAL_HOST=haproxy.pknw1.co.uk
            - VIRTUAL_PORT=70
        networks:
          - proxy

    haproxy-ui:
        image: pknw1/haproxy-manager-ui:dev
        volumes:
          - ./config/haproxy:/etc/haproxy
        ports:
          - "172.18.0.1:5000:5000"
        environment:
          - VIRTUAL_HOST=haui.pknw1.co.uk
          - VIRTUAL_PORT=5000
          - VIRTUAL_PROTO=http
        networks:
          - proxy

    proxy:
        image: nginxproxy/nginx-proxy:latest
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/ssl:/etc/ssl:ro
            - /var/run/docker.sock:/var/run/docker.sock
            - /var/run/docker.sock:/tmp/docker.sock
            - ./config/proxy/etc/certs:/etc/nginx/certs
        ports:
            - "172.18.0.1:8088:80"
        environment:
            - VIRTUAL_HOST=proxy.pknw1.co.uk
            - VIRTUAL_PORT=80
            - VIRTUAL_PROTO=http
        networks:
          - proxy

networks:
  proxy:
      name: proxy
      external: true
